spring:
  application:
    name: export-batch-app
    language:
      es: es_ES
      en: en_US
  # Liguibase
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    #contexts: dev,export-batch-dev
    contexts: export-batch-dev
    label-filter: export-batch-dev
  # maria db docker
  datasource:
    url: jdbc:mariadb://localhost:3307/film?createDatabaseIfNotExist=true
    username: root
    password: dbpw
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        transaction:
          jta:
            platform: org.hibernate.service.jta.platform.internal.JBossStandAloneJtaPlatform
    #validate, none, update, create-drop
    hibernate:
      ddl-auto: validate
# Configuración de Spring Batch
  batch:
    jdbc:
      initialize-schema: always
  sql:
    init:
      platform: mariadb
server:
  port: 9096

#logging:
#  level:
#    org:
#      h2: DEBUG
#      hibernate: DEBUG
#      springframework:
#        web: DEBUG
#        batch: DEBUG
#  logging.level.org.hibernate.SQL=DEBUG
#  logging.level.org.hibernate.transaction=TRACE