
spring:
  application:
    name: ratings-api
# Liguibase
  liquibase:
    enabled: false
  # h2
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        transaction:
          jta:
            platform: org.hibernate.service.jta.platform.internal.JBossStandAloneJtaPlatform
    #validate, none, update, create-drop
    hibernate:
      ddl-auto: create-drop
    # Debug queries
    show-sql: true
  test:
    database:
      replace: none
server:
  port: 9096

application:
  # JWT Token
  jwt:
    secret: 1r9yBxxxPu/H6tfN+V58+qfBXIdNwRiJLgbQo6NU8IyzkmTUzwbjW19fYkvFDZHTETCKdGPlsl8KLXlDJLe6czQphUHkZsyDSbErmmqxrwSbkM4IWZ1GsX2HznDuffz5y7T+O9rUrX9rmIKTIW2PEOrn5YSW7fqypLBN9ru8ttzphF+8Oe97SmxyCUCMvM0WyeF3aW9RV9PY2ga695vr62OV3Hs9Nq52kzZN0Q/R+LwMNsHzeuWdE9Bb7kmcbPUrTI08bJJ6YzFXbehb8V3unZy9KRz8VRj89TL3gE/+EVnrDskTDUDteJCDp2/8tQXbheg37g54/n72Q/e2+kXjC5whLbT7LHEtRZGSe1nB9k583pRw5D9f5ksyvIdLdcbvBnyAVXzmqsOROwVlkwaNQL707OHpxM77RWdHObXUSLI=
    expiration: PT1H

# log console
logging:
  level:
    org:
      springframework:
        security: WARN
        oauth2: WARN
        web: WARN

# actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true