
spring:
  application:
    name: film-web
    # Liguibase
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    contexts: dev
    label-filter: film-web-dev
  # h2 database
  datasource:
    # jdbc:h2:file:C:/Users/andre/Documents/SourceTree/SpringCinemaApplication/film-bbdd/filmdb
    url: jdbc:h2:file:../film-bbdd/filmdb
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
  sql:
    init:
      platform: h2
  web:
    locale: es
    # evita que Spring sirva recursos estáticos por defecto desde /static, /publi
#    resources:
#      add-mappings: false
  messages:
    encoding: UTF-8
  servlet:
    # Session
    session:
      timeout: 15m
      tracking-modes: COOKIE
    # Multipart
    multipart:
      max-file-size: 2MB
  # Hace que en lugar de devolver un 404 plano, Spring lance una excepción NoHandlerFoundException
#  mvc:
#    throw-exception-if-no-handler-found: true
# Spring aplica automáticamente esos formatos por defecto cuando hace binding de parámetros de formulario, query params, path variables o JSON hacia LocalDate, LocalDateTime y LocalTime, y viceversa
# evita que tengamos que usar @DateTimeFormat(pattern = "yyyy-MM-dd'T'HH:mm:ss") en los los dto, entities, controladores
# ya que lo tomara de la configuración
# deprecado en Spring 6.0, o Spring Boot 3, pero se puede seguir usando
# no recomendado desde Spirng boot 2.6+
#mvc:
#  format:
#    date-time: "yyyy-MM-dd'T'HH:mm:ss"
#    date: "yyyy-MM-dd"
#    time: "HH:mm:ss"
server:
  port: 8083
  # Hace que en lugar de devolver un 404 plano, Spring lance una excepción NoHandlerFoundException, Spring Boot 3.x+
  error:
    whitelabel:
      enabled: false
      # Actuator:
# Activar endpoints predefinidos: management.endpoints.web.exposure.include= .....
# Desactivar un edpoint: management.endpoint.health.enable= false/true
management:
  endpoints:
    web:
      exposure:
        include: health, bean, info, auditevents, env, sessions, shutdown, metrics, prometheus, logfile, loggers, configprops, conditions
  endpoint:
    health:
      enabled: false

logging:
  level:
    org:
      h2: DEBUG
      hibernate: DEBUG
      springframework:
        security: DEBUG
        web: DEBUG
#logging.level.org.hibernate.SQL=DEBUG
#logging.level.org.hibernate.transaction=TRACE

# Clave secreta del servidor que Spring Security usa para firmar y validar la cookie remember-me
# si cambia, invalida todas las cookies remember-me
security:
  remember-me:
    key: e2d453aa-909d-4f3e-8b20-b33c5177fb9c