spring:
  application:
    name: file-store-api
  # redis connection
  data:
    redis:
      host: localhost
      port: 6379

server:
  port: 9091

# Actuator:
# Activar endpoints predefinidos: management.endpoints.web.exposure.include= .....
# Desactivar un edpoint: management.endpoint.health.enable= false/true
management:
  endpoints:
    web:
      exposure:
        include: health, bean
  endpoint:
    health:
      enabled: false

application:
  store:
    # Dinamic resource path
    absolute-path: C:\Users\andre\Documents\SourceTree\SpringCinemaApplication\resources\test
    relative-path: ..\..\resources\test
    # User in memory
    login:
      users:
        - username: user
          # password = "password", https://bcrypt-generator.com/ {bcrypt}$2a$15$gOuw1rrOG3J4GzXnfqHo5uxG2E5dDgAyJFpB4B.PA8VL9nxjA6n9m
          password: "$2a$15$gOuw1rrOG3J4GzXnfqHo5uxG2E5dDgAyJFpB4B.PA8VL9nxjA6n9m"
          authorities: read-resource
          roles: admin
        - username: admin
          # password = "password", https://bcrypt-generator.com/ {bcrypt}$2a$15$gOuw1rrOG3J4GzXnfqHo5uxG2E5dDgAyJFpB4B.PA8VL9nxjA6n9m
          password: "$2a$15$gOuw1rrOG3J4GzXnfqHo5uxG2E5dDgAyJFpB4B.PA8VL9nxjA6n9m"
          authorities: read-resource, write-resource
          roles: USER, ADMIN
  # JWT Token
  jwt:
    secret: 1r9yBxxxPu/H6tfN+V58+qfBXIdNwRiJLgbQo6NU8IyzkmTUzwbjW19fYkvFDZHTETCKdGPlsl8KLXlDJLe6czQphUHkZsyDSbErmmqxrwSbkM4IWZ1GsX2HznDuffz5y7T+O9rUrX9rmIKTIW2PEOrn5YSW7fqypLBN9ru8ttzphF+8Oe97SmxyCUCMvM0WyeF3aW9RV9PY2ga695vr62OV3Hs9Nq52kzZN0Q/R+LwMNsHzeuWdE9Bb7kmcbPUrTI08bJJ6YzFXbehb8V3unZy9KRz8VRj89TL3gE/+EVnrDskTDUDteJCDp2/8tQXbheg37g54/n72Q/e2+kXjC5whLbT7LHEtRZGSe1nB9k583pRw5D9f5ksyvIdLdcbvBnyAVXzmqsOROwVlkwaNQL707OHpxM77RWdHObXUSLI=
    expiration: PT1H

logging:
  level:
    org:
      springframework:
        security: DEBUG
        oauth2: DEBUG
        web: DEBUG
    com.tokioschool.storeapp: DEBUG