
spring:
  application:
    name: film-api
# Liguibase
  liquibase:
    enabled: false
  # maria db d
  datasource:
    url: jdbc:h2:mem:test_mail_db;MODE=MariaDB;DATABASE_TO_LOWER=TRUE;
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    #validate, none, update, create-drop
    hibernate:
      ddl-auto: create-drop
    # Debug queries
    show-sql: true
  # redis connection
  data:
    redis:
      host: localhost
      port: 6379
  test:
    database:
      replace: none
server:
  port: 9090

application:
  # JWT Token
  jwt:
    secret: 1r9yBxxxPu/H6tfN+V58+qfBXIdNwRiJLgbQo6NU8IyzkmTUzwbjW19fYkvFDZHTETCKdGPlsl8KLXlDJLe6czQphUHkZsyDSbErmmqxrwSbkM4IWZ1GsX2HznDuffz5y7T+O9rUrX9rmIKTIW2PEOrn5YSW7fqypLBN9ru8ttzphF+8Oe97SmxyCUCMvM0WyeF3aW9RV9PY2ga695vr62OV3Hs9Nq52kzZN0Q/R+LwMNsHzeuWdE9Bb7kmcbPUrTI08bJJ6YzFXbehb8V3unZy9KRz8VRj89TL3gE/+EVnrDskTDUDteJCDp2/8tQXbheg37g54/n72Q/e2+kXjC5whLbT7LHEtRZGSe1nB9k583pRw5D9f5ksyvIdLdcbvBnyAVXzmqsOROwVlkwaNQL707OHpxM77RWdHObXUSLI=
    expiration: PT1H
  # Store
  store:
    base-url: http://localhost:9091
    # User in memory
    login:
      users:
        - username: consumer
          # password = "password", https://bcrypt-generator.com/ {bcrypt}$2a$15$gOuw1rrOG3J4GzXnfqHo5uxG2E5dDgAyJFpB4B.PA8VL9nxjA6n9m
          # "password" in base64:: cGFzc3dvcmQ=
          password: cGFzc3dvcmQ=
        - username: producer
          # password = "password", https://bcrypt-generator.com/ {bcrypt}$2a$15$gOuw1rrOG3J4GzXnfqHo5uxG2E5dDgAyJFpB4B.PA8VL9nxjA6n9m
          # "password" in base64:: cGFzc3dvcmQ=
          password: cGFzc3dvcmQ=

# log console
logging:
  level:
    org:
      springframework:
        security: WARN
        oauth2: WARN
        web: WARN
    com.tokioschool.storeapp: WARN